language: ruby
rvm:
  - 2.6.5
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rails db:migrate --trace
  - bundle exec rspec spec/models
services:
  - postgresql