language: ruby
rvm:
  - 2.6.5
before_script:
  - psql -c 'create database db_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/models
services:
  - postgresql